project:
  type: website
  output-dir: _site

website:
  title: "**Data Wrangling and Visualization**"
  site-url: https://jacklreilly.github.io/dwv_f25/
  repo-url: https://github.com/jacklreilly/dwv_f25
  navbar:
    left:
      - href: overview.qmd
        text: ğŸ“š Overview
      - href: schedule.qmd
        text: ğŸ“… Schedule
      - href: assignments/index.qmd
        text: ğŸ“ Content
      - href: policies.qmd
        text: ğŸ« Policies
      - href: ai.qmd
        text: ğŸ¤– AI & LLMs
  page-footer:
    left: |
      Built with [Quarto](https://quarto.org)
    center: |
      Â© 2025 Jack Reilly
    right: |
      [Contact](mailto:jlreilly@syr.edu)

  sidebar:
    - id: assign
      style: docked
      search: true
      contents:
        - section: "Weekly Content"
          href: assignments/index.qmd
          contents:
          - assignments/assign1.qmd
          - assignments/assign2.qmd
          - assignments/assign3.qmd
          - assignments/assign4.qmd
          - assignments/assign5.qmd
          - assignments/assign6.qmd
          - assignments/assign7.qmd
          - assignments/assign8.qmd
          - assignments/assign9.qmd
          - assignments/assign10.qmd
          - assignments/assign11.qmd
          - assignments/assign12.qmd
          - assignments/assign13.qmd
          - assignments/assign14.qmd
          - assignments/assign15.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
execute:
  freeze: auto



